"""Add title and timestamps to objectives

Revision ID: a82106a9de1d
Revises: 873a3396bead
Create Date: 2025-01-01 01:45:35.032679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82106a9de1d'
down_revision: Union[str, None] = '873a3396bead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add title columns as nullable first
    op.add_column('enabling_objectives', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('enabling_objectives', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('enabling_objectives', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('terminal_objectives', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('terminal_objectives', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('terminal_objectives', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE enabling_objectives SET title = description")
    op.execute("UPDATE terminal_objectives SET title = description")

    # Make title columns non-nullable
    op.alter_column('enabling_objectives', 'title',
               existing_type=sa.String(length=255),
               nullable=False)
    op.alter_column('terminal_objectives', 'title',
               existing_type=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal_objectives', 'updated_at')
    op.drop_column('terminal_objectives', 'created_at')
    op.drop_column('terminal_objectives', 'title')
    op.drop_column('enabling_objectives', 'updated_at')
    op.drop_column('enabling_objectives', 'created_at')
    op.drop_column('enabling_objectives', 'title')
    # ### end Alembic commands ###
